#server.port=8080
#
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:mysql://localhost:3306/sakila
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=Dashok_191
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
#jwt.secret=your-256-bit-secret-key-with-at-least-32-characters
#jwt.expiration=86400000 # 24 часа

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sakila
    username: root
    password: Dashok_191
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate: debug

jwt:
  secret: your.256.bit.secret.key.with.at.least.32.characters
  expiration: 86400000